### ISSUE TITLE
v0.1.0 release overview

### ISSUE THREAD

**Issue by guylepage3** [blockstack/design-system#1]
@guylepage3 commented on [Thu Apr 06 2017](https://github.com/blockstack/designs/issues/233)

### Highlights
- Definition of Blockstack Design System
- Table of contents defined
- Initial MVP documentation

#### Tasks
- [ ] https://github.com/blockstack/design-system/issues/4: review design system sketch file for inconsistencies
- [ ] https://github.com/blockstack/design-system/issues/3: blockstack design system - BlockstackDS
- [ ] https://github.com/blockstack/design-system/issues/2: design system response to josh hynes (stackoverflow) medium post

### Bugs
- [ ] n/a
